_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_steps: 100_000
max_steps: 400_000

log_every_n_steps: 100
val_check_interval: 5_000
gradient_clip_val: 1.0

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
precision: bf16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: null

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
