# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/launcher: ray
  - override /experiment: ksin/flow
  - override /hydra/sweeper: optuna
  - _self_

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: 'val/lsd'

trainer:
  devices: 1
  accelerator: gpu
  strategy: auto
  min_epochs: 500
  max_epochs: 500

data:
  k: 8

logger:
  wandb:
    group: sweep
    name: null

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
num_gpus: 3
n_jobs: 3
hydra:
  mode: 'MULTIRUN' # set hydra to multirun by default if this config is attached

  launcher:
    ray:
      init:
        num_gpus: ${num_gpus}
        local_mode: false
      remote:
        num_gpus: 1.0
        max_calls: 1

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: ksin

    # number of parallel workers
    n_jobs: ${n_jobs}

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 100

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 6 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      model.optimizer.lr: tag(log, interval(0.000001, 0.001))
      model.encoder.out_dim: choice(32, 64, 128, 256, 512, 1024)
      model.encoder.hidden_dim: choice(128, 512, 1024, 2048)
      model.encoder.num_blocks: choice(2, 3, 4, 5, 6, 7, 8)
      model.vector_field.hidden_dim: choice(128, 512, 1024, 2048)
      model.vector_field.num_blocks: choice(2, 3, 4, 5, 6, 7, 8)
      model.coupling: choice(uniform, kabsch, procrustes)
      model.probability_path: choice(rectified, cfm, fm)
      model.p_time: choice(uniform, lognormal, beta)
      model.w_time: choice(none, flatten)
      model.cfg_dropout_rate: interval(0.0, 0.3)
      model.cfm_sigma: tag(log, interval(1e-5, 1e-1))
      model.fm_sigma: tag(log, interval(1e-5, 1e-1))
      model.rectified_sigma_min: tag(log, interval(1e-8, 1e-3))
