defaults:
  - surge_flow
  - _self_

encoder:
  d_model: 64
  n_heads: 2
  n_layers: 2

vector_field:
  projection:
    _target_: src.models.components.transformer.LearntProjection
    num_tokens: 16
  num_layers: 3
  d_model: 64
  num_heads: 2
  d_ff: 64
