defaults:
  - _self_

_target_: src.models.surge_ff_module.SurgeFeedForwardModule

net:
  _target_: src.models.components.transformer.ASTWithProjectionHead
  d_model: 768
  d_out: 90
  n_heads: 12
  n_layers: 16
  patch_size: 16
  patch_stride: 10
  input_channels: 2
  spec_space: [128, 401]

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_steps}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

# compile model for faster training with pytorch 2.0
compile: true
