defaults:
  - _self_

_target_: src.models.surge_flowvae_module.SurgeFlowVAEModule

net:
  _target_: src.models.components.vae.FlowVAE
  latent_dim: 92
  encoder:
    _target_: src.models.components.vae.Encoder
    latent_dim: ${model.net.latent_dim}
  decoder:
    _target_: src.models.components.vae.Decoder
    latent_dim: ${model.net.latent_dim}
    num_channels: 2

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_steps}
  eta_min: ${mul:${model.optimizer.lr},1e-2}

warmup_steps: 0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

beta_max: 0.01
beta_start: 0.0

# compile model for faster training with pytorch 2.0
compile: true
