# @package _global_

defaults:
  - _self_
  - data: surge_mini # choose datamodule with `test_dataloader()` for evaluation
  - model: surge_flow
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: eval_surge
  - experiment: null

task_name: "eval"

tags: ["dev"]
mode: test

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
